name: Build and Publish
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build Angular
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout out repository
        uses: actions/checkout@v2
      - name: Use Node.js 12.8
        uses: actions/setup-node@v1
        with:
          node-version: 12.8
      - name: Install NPM dependencies
        run: npm install
      - name: Audit NPM packages
        run: npm audit
      - name: Build NPM App
        run: npm run build -- --prod
      - name: Deploy to GitHub Pages
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com 
          npm run deploy:github -- --no-silent
      - name: Archive production artifacts
        uses: actions/upload-artifact@v1
        with:
          name: dist
          path: dist
  publish:
    name: Publish web artifacts
    if: contains(github.ref, 'main')
    runs-on: ubuntu-18.04
    needs: build
    steps:
      - name: Checkout out repository
        uses: actions/checkout@v2
      - name: Download web dist from build job
        uses: actions/download-artifact@v1
        with:
          name: dist
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'
      - name: Run Ansible playbook through pipenv
        shell: bash
        env:
          AWS_ACCESS_KEY_ID : ${{ secrets.AWS_ACCESSS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
        run: |
          pip install pipenv
          cd $GITHUB_WORKSPACE
          pipenv install
          pipenv run ansible-playbook ansible/playbook.yml
